package com.auvdidao.a12teachingagent.knowledge;

/**
 * Dense refresh counts are scoped to the requested project/material except for
 * embeddedCount, which reports the actual number of vectors generated by the
 * provider. A material-triggered project-wide refresh therefore may have an
 * embeddedCount larger than chunkCount, while reusedCount and refreshedCount
 * remain request-scope counts.
 */
public record DenseRefreshResult(
        Long projectId,
        Long materialId,
        String provider,
        String model,
        long chunkCount,
        long embeddedCount,
        long reusedCount,
        long refreshedCount,
        Integer dimensions,
        boolean denseReady
) {
}
