"""Build the independent PPT visual-QA holdout fixture.

The clean source images are generated by the real isolated PPT Skill Runner.
Broken cases are deterministic image mutations applied only after that real
render, and are recorded in the immutable Gold Set with their source slide and
mutation description.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import random
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable, Iterable

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parent
DEFAULT_OUT = ROOT / "visual-qa-holdout"
RUNNER_URL = os.environ.get("PPT_VISUAL_QA_HOLDOUT_RUNNER_URL", "http://127.0.0.1:38090").rstrip("/")
STYLE_PRESET = "forest-research"

OBJECTIVE_CODES = [
    "TEXT_OVERFLOW", "TEXT_TOO_SMALL", "ELEMENT_OVERLAP", "ELEMENT_CLIPPED",
    "LOW_CONTRAST", "TABLE_UNREADABLE", "CHART_UNREADABLE", "FLOW_UNREADABLE",
    "BROKEN_RENDERING",
]
SUBJECTIVE_CODES = [
    "UNBALANCED_LAYOUT", "EXCESSIVE_EMPTY_SPACE", "VISUAL_HIERARCHY_WEAK", "DENSE_CONTENT",
]


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    candidates = [
        Path("C:/Windows/Fonts/segoeuib.ttf" if bold else "C:/Windows/Fonts/segoeui.ttf"),
        Path("C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf"),
        Path("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
    ]
    for candidate in candidates:
        if candidate.exists():
            return ImageFont.truetype(str(candidate), size)
    return ImageFont.load_default()


def outline() -> dict:
    return {
        "title": "Independent Visual QA Holdout",
        "subtitle": "Deterministic Runner fixture with unseen layouts and controlled mutations",
        "deck_style": {
            "visual_density": "medium",
            "header_variant": "auto",
            "style_seed": "ppt-016-independent-holdout-v2",
            "footer_page_numbers": True,
        },
        "slides": [
            {"type": "title", "title": "Independent Visual QA Holdout", "subtitle": "PPT-016 · frozen evaluation set"},
            {"type": "content", "variant": "cards-3", "title": "Evaluation agenda", "subtitle": "A compact route through the evidence", "cards": [
                {"title": "Observe", "body": "Inspect the rendered slide itself", "accent": "accent_primary"},
                {"title": "Compare", "body": "Separate objective defects from preferences", "accent": "accent_secondary"},
                {"title": "Decide", "body": "Keep automatic blocking out of scope", "accent": "accent_primary"},
            ]},
            {"type": "content", "variant": "split", "title": "What makes a defect real?", "subtitle": "Concept and evidence", "bullets": [
                "The visible problem must harm reading or use",
                "The affected element and location must be identifiable",
                "A repair hint must describe a concrete correction",
            ], "highlights": ["Visible evidence before interpretation", "Readable does not mean perfect"]},
            {"type": "content", "variant": "comparison-2col", "title": "Signal versus preference", "subtitle": "A clean comparison page", "left": {"title": "Signal", "body": "A clipped label, unreadable table, or broken reading path"}, "right": {"title": "Preference", "body": "A different color choice, ordinary whitespace, or mild asymmetry"}, "verdict": "Only visible material defects belong in the issue list."},
            {"type": "content", "variant": "timeline", "title": "The evaluation process", "subtitle": "From source fixture to decision", "milestones": [
                {"label": "01", "title": "Render", "body": "Build a deterministic outline with the real Runner."},
                {"label": "02", "title": "Mutate", "body": "Apply a recorded, visible holdout-only mutation."},
                {"label": "03", "title": "Review", "body": "Run one baseline call and one Candidate A call."},
                {"label": "04", "title": "Audit", "body": "Compare hard-fail, code, group, and actionability metrics."},
            ]},
            {"type": "content", "variant": "chart", "title": "Readable chart baseline", "subtitle": "A clean data page", "chart": {"type": "line", "series": [{"name": "Observed signal", "labels": ["A", "B", "C", "D", "E"], "values": [12, 18, 16, 25, 31]}], "options": {}}, "facts": [{"value": "31", "label": "latest value", "detail": "A single series with explicit labels."}, {"value": "2.6x", "label": "range", "detail": "The chart remains legible at slide scale."}], "caption": "Illustrative deterministic data; no factual claim is evaluated."},
            {"type": "content", "variant": "table", "title": "Readable decision table", "subtitle": "A clean tabular page", "table": {"headers": ["Condition", "Evidence", "Action"], "rows": [["Clear label", "Visible", "Keep"], ["Strong contrast", "Readable", "Keep"], ["Useful spacing", "Balanced", "Keep"]]}},
            {"type": "content", "variant": "cards-3", "title": "Causal diagram", "subtitle": "Diagram-like nodes with a clear left-to-right path", "cards": [
                {"title": "Input", "body": "Source image and slide context", "accent": "accent_primary"},
                {"title": "Inspection", "body": "Visible evidence and issue taxonomy", "accent": "accent_secondary"},
                {"title": "Decision", "body": "Advisory result, never an automatic block", "accent": "accent_primary"},
            ], "highlights": ["Input → inspection → decision"]},
            {"type": "content", "variant": "standard", "title": "Activity and assessment", "subtitle": "A clean classroom interaction page", "body": "Ask reviewers to mark the first visible reading failure, then explain why it matters.", "bullets": ["Point to the affected element", "Name the issue code", "Separate a defect from a design preference"], "highlights": ["One observation", "One reason", "One repair direction"]},
            {"type": "content", "variant": "cards-2", "title": "Holdout summary", "subtitle": "What the evaluation should protect", "cards": [
                {"title": "Clean slides", "body": "Do not turn ordinary layouts into false hard failures", "accent": "accent_primary"},
                {"title": "Broken slides", "body": "Do not lose material defects when layouts become complex", "accent": "accent_secondary"},
            ]},
            {"type": "content", "variant": "stats", "title": "Coverage snapshot", "subtitle": "A clean summary page", "stats": [{"value": "13", "label": "issue codes", "detail": "Objective and subjective taxonomy."}, {"value": "2", "label": "prompt variants", "detail": "Baseline and frozen Candidate A."}, {"value": "1", "label": "decision", "detail": "Generalization is the only conclusion."}]},
            {"type": "content", "variant": "standard", "title": "Final review question", "subtitle": "Independent holdout", "body": "Does Candidate A preserve clean-slide safety while improving objective defect precision on layouts it has never seen?", "bullets": ["Clean hard-fail must not worsen", "Objective precision should improve", "Broken hard-fail recall must not collapse"], "highlights": ["Best observed is not production-ready"]},
        ],
    }


def call_runner(out_dir: Path) -> dict:
    payload = json.dumps({"outline": outline(), "stylePreset": STYLE_PRESET}).encode("utf-8")
    request = urllib.request.Request(
        f"{RUNNER_URL}/internal/ppt-skill/v1/generations",
        data=payload,
        headers={"Content-Type": "application/json; charset=utf-8"},
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=900) as response:
        result = json.loads(response.read().decode("utf-8"))
    (out_dir / "runner-generation.json").write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    for slide_number in range(1, len(outline()["slides"]) + 1):
        url = f"{RUNNER_URL}/internal/ppt-skill/v1/jobs/{result['jobId']}/previews/{slide_number}"
        with urllib.request.urlopen(url, timeout=120) as response:
            (out_dir / f"source-slide-{slide_number:02d}.png").write_bytes(response.read())
    return result


def overlay(image: Image.Image) -> tuple[Image.Image, ImageDraw.ImageDraw]:
    layer = Image.new("RGBA", image.size, (0, 0, 0, 0))
    return layer, ImageDraw.Draw(layer)


def apply_layer(image: Image.Image, layer: Image.Image) -> Image.Image:
    return Image.alpha_composite(image.convert("RGBA"), layer).convert("RGB")


def mutate_text_overflow(image: Image.Image) -> Image.Image:
    w, h = image.size
    layer, draw = overlay(image)
    draw.rounded_rectangle((int(w * .56), int(h * .76), w + 90, h + 45), radius=12, fill=(21, 48, 70, 245))
    draw.text((int(w * .58), int(h * .79)), "A long footer annotation is clipped at the bottom edge", font=font(26), fill=(248, 180, 62, 255))
    return apply_layer(image, layer)


def mutate_text_too_small(image: Image.Image) -> Image.Image:
    w, h = image.size
    layer, draw = overlay(image)
    draw.rectangle((int(w * .10), int(h * .84), int(w * .90), int(h * .96)), fill=(247, 245, 235, 240))
    tiny = font(8)
    for index in range(8):
        draw.text((int(w * .12), int(h * (.845 + index * .013))), "footnote label / source reference / observation", font=tiny, fill=(92, 103, 110, 255))
    return apply_layer(image, layer)


def mutate_overlap(image: Image.Image) -> Image.Image:
    w, h = image.size
    layer, draw = overlay(image)
    draw.rounded_rectangle((int(w * .27), int(h * .30), int(w * .76), int(h * .72)), radius=16, fill=(13, 84, 87, 235))
    draw.rounded_rectangle((int(w * .48), int(h * .51), int(w * .92), int(h * .84)), radius=16, fill=(217, 82, 57, 245))
    draw.text((int(w * .33), int(h * .47)), "blocked reading path", font=font(28, True), fill=(255, 255, 255, 255))
    return apply_layer(image, layer)


def mutate_clipped(image: Image.Image) -> Image.Image:
    w, h = image.size
    layer, draw = overlay(image)
    draw.rounded_rectangle((w - 160, h - 170, w + 130, h + 95), radius=18, fill=(74, 43, 94, 245), outline=(248, 180, 62, 255), width=8)
    draw.text((w - 140, h - 120), "edge object", font=font(30, True), fill=(255, 255, 255, 255))
    return apply_layer(image, layer)


def mutate_low_contrast(image: Image.Image) -> Image.Image:
    w, h = image.size
    layer, draw = overlay(image)
    draw.rectangle((int(w * .08), int(h * .27), int(w * .92), int(h * .72)), fill=(235, 235, 224, 190))
    draw.text((int(w * .16), int(h * .45)), "important annotation", font=font(32, True), fill=(211, 213, 202, 255))
    draw.text((int(w * .16), int(h * .54)), "low contrast against the panel", font=font(25), fill=(214, 216, 207, 255))
    return apply_layer(image, layer)


def mutate_table(image: Image.Image) -> Image.Image:
    w, h = image.size
    layer, draw = overlay(image)
    top = int(h * .38)
    bottom = int(h * .84)
    draw.rectangle((int(w * .10), top, int(w * .90), bottom), fill=(229, 226, 211, 245), outline=(23, 49, 66, 255), width=5)
    for y in range(top + 42, bottom, 46):
        draw.rectangle((int(w * .10), y, int(w * .90), y + 19), fill=(19, 31, 42, 245))
    for x in [int(w * .36), int(w * .62)]:
        draw.line((x, top, x, bottom), fill=(19, 31, 42, 255), width=5)
    return apply_layer(image, layer)


def mutate_chart(image: Image.Image) -> Image.Image:
    w, h = image.size
    layer, draw = overlay(image)
    draw.rectangle((int(w * .13), int(h * .30), int(w * .87), int(h * .78)), fill=(241, 240, 232, 218))
    for offset in range(0, 18):
        y = int(h * (.34 + offset * .021))
        draw.line((int(w * .17), y, int(w * .84), y), fill=(190, 194, 188, 220), width=3)
    draw.text((int(w * .24), int(h * .48)), "axis labels / legend / values", font=font(9), fill=(196, 198, 191, 255))
    return apply_layer(image, layer)


def mutate_flow(image: Image.Image) -> Image.Image:
    w, h = image.size
    layer, draw = overlay(image)
    for i in range(7):
        x = int(w * (.18 + i * .10))
        draw.line((x, int(h * .28), x + 180, int(h * .80)), fill=(210, 65, 50, 235), width=18)
    for x in [int(w * .20), int(w * .45), int(w * .70)]:
        draw.ellipse((x, int(h * .48), x + 120, int(h * .60)), fill=(18, 67, 83, 245))
    draw.text((int(w * .18), int(h * .65)), "steps cannot be followed", font=font(28, True), fill=(255, 255, 255, 255))
    return apply_layer(image, layer)


def mutate_rendering(image: Image.Image) -> Image.Image:
    w, h = image.size
    layer, draw = overlay(image)
    rng = random.Random(16016)
    for index in range(24):
        y = int(h * .25 + index * h * .022)
        height = rng.randint(7, 19)
        color = (rng.randint(15, 245), rng.randint(15, 245), rng.randint(15, 245), 230)
        draw.rectangle((int(w * (.08 + rng.random() * .08)), y, int(w * (.86 + rng.random() * .12)), y + height), fill=color)
    draw.line((int(w * .12), int(h * .27), int(w * .90), int(h * .80)), fill=(0, 0, 0, 255), width=12)
    return apply_layer(image, layer)


def mutate_unbalanced(image: Image.Image) -> Image.Image:
    w, h = image.size
    layer, draw = overlay(image)
    draw.rectangle((int(w * .58), int(h * .17), int(w * .98), int(h * .92)), fill=(9, 31, 42, 250))
    draw.rounded_rectangle((int(w * .09), int(h * .76), int(w * .25), int(h * .85)), radius=8, fill=(218, 82, 57, 255))
    return apply_layer(image, layer)


def mutate_empty(image: Image.Image) -> Image.Image:
    w, h = image.size
    bg = image.getpixel((2, 2))
    layer, draw = overlay(image)
    draw.rectangle((int(w * .36), int(h * .30), w - 2, h - 2), fill=(*bg, 255))
    draw.rounded_rectangle((int(w * .10), int(h * .58), int(w * .31), int(h * .70)), radius=8, fill=(20, 68, 83, 255))
    draw.text((int(w * .12), int(h * .605)), "one small island", font=font(18, True), fill=(255, 255, 255, 255))
    return apply_layer(image, layer)


def mutate_hierarchy(image: Image.Image) -> Image.Image:
    w, h = image.size
    layer, draw = overlay(image)
    colors = [(48, 83, 91, 245), (48, 83, 91, 245), (48, 83, 91, 245), (48, 83, 91, 245)]
    for index, color in enumerate(colors):
        x = int(w * (.10 + index * .21))
        draw.rounded_rectangle((x, int(h * .38), x + int(w * .16), int(h * .68)), radius=10, fill=color)
        draw.text((x + 18, int(h * .50)), f"block {index + 1}", font=font(24), fill=(224, 224, 215, 255))
    draw.text((int(w * .13), int(h * .73)), "No focal point; equal weight everywhere", font=font(22), fill=(36, 50, 55, 255))
    return apply_layer(image, layer)


def mutate_dense(image: Image.Image) -> Image.Image:
    w, h = image.size
    layer, draw = overlay(image)
    tiny = font(10)
    for row in range(13):
        y = int(h * .27 + row * h * .043)
        for col in range(6):
            x = int(w * .08 + col * w * .145)
            draw.rectangle((x, y, x + int(w * .12), y + 24), fill=(29, 67 + (row % 3) * 18, 79, 230), outline=(227, 171, 69, 255), width=2)
            draw.text((x + 5, y + 6), "dense note", font=tiny, fill=(255, 255, 255, 255))
    return apply_layer(image, layer)


MUTATIONS: dict[str, Callable[[Image.Image], Image.Image]] = {
    "TEXT_OVERFLOW": mutate_text_overflow,
    "TEXT_TOO_SMALL": mutate_text_too_small,
    "ELEMENT_OVERLAP": mutate_overlap,
    "ELEMENT_CLIPPED": mutate_clipped,
    "LOW_CONTRAST": mutate_low_contrast,
    "TABLE_UNREADABLE": mutate_table,
    "CHART_UNREADABLE": mutate_chart,
    "FLOW_UNREADABLE": mutate_flow,
    "BROKEN_RENDERING": mutate_rendering,
    "UNBALANCED_LAYOUT": mutate_unbalanced,
    "EXCESSIVE_EMPTY_SPACE": mutate_empty,
    "VISUAL_HIERARCHY_WEAK": mutate_hierarchy,
    "DENSE_CONTENT": mutate_dense,
}


BROKEN_CASES = [
    ("broken-01-text-overflow", 5, "process", ["TEXT_OVERFLOW"], "ERROR", "Bottom-right multi-line footer crosses the lower canvas edge; different location and text shape from Development Set."),
    ("broken-02-text-too-small", 9, "activity-assessment", ["TEXT_TOO_SMALL"], "WARNING", "A dense eight-line source strip is reduced to genuinely tiny labels in a footer region."),
    ("broken-03-overlap-complex", 4, "comparison", ["ELEMENT_OVERLAP", "ELEMENT_CLIPPED"], "ERROR", "Two opaque panels cover the comparison middle and lower-right reading path."),
    ("broken-04-clipped-edge", 11, "summary", ["ELEMENT_CLIPPED"], "ERROR", "A new status object extends past the right and bottom edges on a summary page."),
    ("broken-05-low-contrast", 3, "concept", ["LOW_CONTRAST"], "WARNING", "The central concept annotation is painted in near-background tones over a pale panel."),
    ("broken-06-table-complex", 7, "table", ["TABLE_UNREADABLE", "TEXT_TOO_SMALL"], "ERROR", "Heavy dark bars cross rows while tiny source labels occupy the table footer."),
    ("broken-07-chart-complex", 6, "chart", ["CHART_UNREADABLE", "LOW_CONTRAST"], "ERROR", "Chart plot, axis labels, and legend are washed into a low-contrast band."),
    ("broken-08-flow-complex", 5, "process", ["FLOW_UNREADABLE", "ELEMENT_OVERLAP"], "ERROR", "Diagonal crossing connectors cover process nodes and interrupt the path."),
    ("broken-09-rendering-complex", 12, "assessment", ["BROKEN_RENDERING", "ELEMENT_CLIPPED"], "ERROR", "Offset multicolor raster bands and a diagonal tear corrupt the rendered assessment page."),
    ("broken-10-unbalanced", 2, "agenda", ["UNBALANCED_LAYOUT"], "WARNING", "A dominant dark right rail overwhelms a small left-side agenda accent."),
    ("broken-11-empty-space", 10, "summary", ["EXCESSIVE_EMPTY_SPACE"], "WARNING", "Most lower-right content is erased, leaving one small content island."),
    ("broken-12-hierarchy", 8, "diagram", ["VISUAL_HIERARCHY_WEAK"], "WARNING", "Four equal-weight nodes replace the original focal path on a diagram-like page."),
    ("broken-13-dense-complex", 11, "summary", ["DENSE_CONTENT", "TEXT_TOO_SMALL"], "WARNING", "A thirteen-row by six-column note grid crowds a previously sparse summary."),
    ("broken-14-chart-small", 6, "chart", ["CHART_UNREADABLE", "TEXT_TOO_SMALL"], "ERROR", "The second chart mutation compresses labels into a tiny noisy strip rather than masking the plot."),
    ("broken-15-overflow-overlap", 9, "activity-assessment", ["TEXT_OVERFLOW", "ELEMENT_OVERLAP"], "ERROR", "A clipped footer banner overlays the assessment instruction area."),
    ("broken-16-table-contrast", 7, "table", ["TABLE_UNREADABLE", "LOW_CONTRAST"], "ERROR", "Table rows are low-contrast and partially occluded by dark separators."),
    ("broken-17-flow-clipped", 5, "timeline-process", ["FLOW_UNREADABLE", "ELEMENT_CLIPPED"], "ERROR", "Process route is crossed by clipped nodes at the lower edge."),
    ("broken-18-rendering-contrast", 12, "assessment", ["BROKEN_RENDERING", "LOW_CONTRAST"], "ERROR", "Raster corruption is combined with a pale overlay that removes readable contrast."),
]


def build_gold(out_dir: Path) -> list[dict]:
    cases: list[dict] = []
    clean_types = [
        (1, "cover"), (2, "agenda"), (3, "concept"), (4, "comparison"),
        (5, "timeline-process"), (6, "chart"), (7, "table"), (8, "diagram"),
        (9, "activity-assessment"), (10, "summary"), (11, "summary-stats"), (12, "assessment"),
    ]
    clean_file_by_slide = {slide_number: f"clean-{slide_number:02d}-{slide_type}.png" for slide_number, slide_type in clean_types}
    source_fixture = "ppt-skill-runner:deterministic-holdout-outline-v1"
    for slide_number, slide_type in clean_types:
        source_name = f"source-slide-{slide_number:02d}.png"
        file_name = f"clean-{slide_number:02d}-{slide_type}.png"
        source_path = out_dir / source_name
        clean_path = out_dir / file_name
        if source_path.exists():
            source_path.replace(clean_path)
        elif not clean_path.exists():
            raise FileNotFoundError(f"Missing Runner clean source: {source_path}")
        cases.append({
            "caseId": f"clean-{slide_number:02d}-{slide_type}",
            "fileName": file_name,
            "slideNumber": slide_number,
            "slideType": slide_type,
            "knownClean": True,
            "expectedCodes": [],
            "expectedMaxSeverity": "INFO",
            "notes": "Fresh real Runner-rendered clean holdout slide; not copied from Development Gold Set.",
            "sourceFixture": source_fixture,
            "mutationDescription": "none",
            "sourceSlideNumber": slide_number,
        })
    for index, (case_id, source_slide, slide_type, expected_codes, severity, mutation_description) in enumerate(BROKEN_CASES, start=1):
        source_path = out_dir / clean_file_by_slide[source_slide]
        output_name = f"{case_id}.png"
        source_image = Image.open(source_path).convert("RGB")
        mutated = MUTATIONS[expected_codes[0]](source_image)
        # Apply a second mutation only where the Gold label contains a real
        # second defect; this keeps combined cases materially multi-defect.
        if len(expected_codes) > 1:
            mutated = MUTATIONS[expected_codes[1]](mutated)
        mutated.save(out_dir / output_name, format="PNG", optimize=True)
        cases.append({
            "caseId": case_id,
            "fileName": output_name,
            "slideNumber": 1,
            "slideType": slide_type,
            "knownClean": False,
            "expectedCodes": expected_codes,
            "expectedMaxSeverity": severity,
            "notes": "Fresh Runner source with a holdout-only visible mutation; expected codes are frozen before Kimi calls.",
            "sourceFixture": source_fixture,
            "mutationDescription": mutation_description,
            "sourceSlideNumber": source_slide,
        })
    return cases


def make_integrity_report(out_dir: Path, cases: list[dict], runner_result: dict) -> dict:
    all_hashes: dict[str, str] = {}
    observations = []
    clean_sources = {case["caseId"]: out_dir / case["fileName"] for case in cases if case["knownClean"]}
    clean_by_slide = {case["sourceSlideNumber"]: out_dir / case["fileName"] for case in cases if case["knownClean"]}
    for case in cases:
        path = out_dir / case["fileName"]
        with Image.open(path) as image:
            image.load()
            width, height = image.size
            pixels = list(image.convert("RGB").getdata())
        digest = sha256(path)
        duplicate_of = all_hashes.get(digest)
        all_hashes[digest] = case["caseId"]
        source_path = clean_by_slide.get(case["sourceSlideNumber"])
        diff_ratio = 0.0
        if not case["knownClean"] and source_path:
            with Image.open(source_path) as source_image:
                source_pixels = list(source_image.convert("RGB").getdata())
            differing = sum(1 for left, right in zip(source_pixels, pixels) if left != right)
            diff_ratio = differing / max(1, len(pixels))
        observations.append({
            "caseId": case["caseId"],
            "fileName": case["fileName"],
            "width": width,
            "height": height,
            "byteSize": path.stat().st_size,
            "sha256": digest,
            "duplicateOf": duplicate_of,
            "nonEmpty": path.stat().st_size > 0 and len(pixels) > 0,
            "mutationVisible": case["knownClean"] or diff_ratio >= 0.002,
            "pixelDiffRatio": round(diff_ratio, 6),
            "sourceFixture": case["sourceFixture"],
        })
    missing_codes = sorted(set(OBJECTIVE_CODES + SUBJECTIVE_CODES) - {code for case in cases for code in case["expectedCodes"]})
    duplicate_cases = [item["caseId"] for item in observations if item["duplicateOf"]]
    invalid_sources = [item["caseId"] for item in observations if item["sourceFixture"] != "ppt-skill-runner:deterministic-holdout-outline-v1"]
    return {
        "version": 2,
        "generatedAt": now_iso(),
        "runner": {"baseUrl": RUNNER_URL, "jobId": runner_result.get("jobId"), "status": runner_result.get("status"), "qaLevel": runner_result.get("qa", {}).get("qaLevel")},
        "caseCount": len(cases),
        "cleanCount": sum(1 for case in cases if case["knownClean"]),
        "brokenCount": sum(1 for case in cases if not case["knownClean"]),
        "dimensions": sorted({f"{item['width']}x{item['height']}" for item in observations}),
        "duplicateCases": duplicate_cases,
        "missingCodes": missing_codes,
        "invalidSourceCases": invalid_sources,
        "allNonEmpty": all(item["nonEmpty"] for item in observations),
        "allMutationsVisible": all(item["mutationVisible"] for item in observations),
        "passed": len(cases) == 30 and not duplicate_cases and not missing_codes and not invalid_sources and all(item["nonEmpty"] for item in observations) and all(item["mutationVisible"] for item in observations),
        "cases": observations,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--skip-runner", action="store_true")
    args = parser.parse_args()
    out_dir = args.out.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    if not args.skip_runner:
        for path in out_dir.glob("*.png"):
            path.unlink()
        runner_result = call_runner(out_dir)
    else:
        runner_result = json.loads((out_dir / "runner-generation.json").read_text(encoding="utf-8"))
    cases = build_gold(out_dir)
    (out_dir / "holdout-runner-outline.json").write_text(json.dumps(outline(), indent=2) + "\n", encoding="utf-8")
    gold = {"version": 2, "source": "PPT-016 independent holdout; labels frozen before Kimi calls", "cases": cases}
    (out_dir / "holdout-gold-set.json").write_text(json.dumps(gold, indent=2) + "\n", encoding="utf-8")
    integrity = make_integrity_report(out_dir, cases, runner_result)
    (out_dir / "holdout-integrity-report.json").write_text(json.dumps(integrity, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"out": str(out_dir), "caseCount": len(cases), "cleanCount": integrity["cleanCount"], "brokenCount": integrity["brokenCount"], "dimensions": integrity["dimensions"], "passed": integrity["passed"]}, indent=2))
    if not integrity["passed"]:
        raise SystemExit("holdout fixture integrity failed")


if __name__ == "__main__":
    main()
