package com.auvdidao.a12teachingagent.config;

import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;

import java.io.IOException;
import java.nio.charset.StandardCharsets;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class PostgresqlMigrationContractTest {

    @Test
    void productionMigrationsAreSeparateFromH2AndCoverBaseAndStage34Schema() throws IOException {
        String baseline = read("db/postgresql-migration/V1__baseline_application_schema.sql");
        String stage34 = read("db/postgresql-migration/V2__stage34_template_spec_integrity.sql");
        String stage8 = read("db/postgresql-migration/V3__stage8_asset_review_manifest.sql");

        String normalized = (baseline + "\n" + stage34 + "\n" + stage8).toLowerCase(java.util.Locale.ROOT);
        assertFalse(normalized.contains("jdbc:h2"));
        assertFalse(normalized.contains("enum ("));
        assertFalse(normalized.contains("clob"));
        assertTrue(normalized.contains("create table projects"));
        assertTrue(normalized.contains("create table templates") || normalized.contains("create table if not exists templates"));
        assertTrue(normalized.contains("create table ppt_specification_versions") || normalized.contains("create table if not exists ppt_specification_versions"));
        assertTrue(normalized.contains("uk_template_profiles_template_version"));
        assertTrue(normalized.contains("ix_ppt_specifications_project_status"));
        assertTrue(normalized.contains("create table candidate_assets") || normalized.contains("create table if not exists candidate_assets"));
        assertTrue(normalized.contains("create table approved_asset_manifests") || normalized.contains("create table if not exists approved_asset_manifests"));
        assertTrue(normalized.contains("active_key"));
        assertTrue(normalized.contains("uk_manifest_project_active_key"));
        assertTrue(normalized.contains("references candidate_assets"));
        assertTrue(normalized.contains("supersedes_manifest_id"));
        assertTrue(normalized.contains("event_checksum"));
    }

    @Test
    void stage9GenerationJobMigrationStoresOnlyBoundInputsAndSafeReceipt() throws IOException {
        String stage9 = read("db/postgresql-migration/V4__stage9_ppt_generation_jobs.sql");
        String normalized = stage9.toLowerCase(java.util.Locale.ROOT);
        assertTrue(normalized.contains("ppt_generation_jobs"));
        assertTrue(normalized.contains("specification_version_id"));
        assertTrue(normalized.contains("template_profile_checksum"));
        assertTrue(normalized.contains("asset_manifest_checksum"));
        assertTrue(normalized.contains("input_identity_checksum"));
        assertTrue(normalized.contains("engine_version"));
        assertTrue(normalized.contains("idempotency_key"));
        assertTrue(normalized.contains("uk_ppt_generation_job_project_idempotency"));
        assertTrue(normalized.contains("uk_ppt_generation_job_execution"));
        assertTrue(normalized.contains("request_snapshot_json"));
        assertTrue(normalized.contains("response_receipt_json"));
        assertFalse(normalized.contains("api_key"));
        assertFalse(normalized.contains("credential varchar"));
    }

    @Test
    void analyzerCandidateIdentityMigrationHasEquivalentH2AndPostgresqlUniqueIndex() throws IOException {
        String h2 = read("db/migration/V10__stage9_analyzer_candidate_identity.sql").toLowerCase(java.util.Locale.ROOT);
        String postgresql = read("db/postgresql-migration/V10__stage9_analyzer_candidate_identity.sql").toLowerCase(java.util.Locale.ROOT);
        for (String migration : new String[]{h2, postgresql}) {
            assertTrue(migration.contains("create unique index"));
            assertTrue(migration.contains("uk_template_profiles_analyzer_identity"));
            assertTrue(migration.contains("project_id"));
            assertTrue(migration.contains("template_id"));
            assertTrue(migration.contains("source_version_id"));
            assertTrue(migration.contains("analysis_run_id"));
            assertTrue(migration.contains("origin"));
        }
    }

    @Test
    void productionLocationContainsLessonForgeV16WithTheSameContractAsH2() throws IOException {
        String h2 = read("db/migration/V16__lessonforge_mission_slice.sql").toLowerCase(java.util.Locale.ROOT);
        String postgresql = read("db/postgresql-migration/V16__lessonforge_mission_slice.sql").toLowerCase(java.util.Locale.ROOT);
        for (String migration : new String[]{h2, postgresql}) {
            assertFalse(migration.contains("clob"));
            assertTrue(migration.contains("generated by default as identity"));
            assertTrue(migration.contains("uk_lf_conversation_mission"));
            assertTrue(migration.contains("ck_lf_submission_rating"));
            for (String table : new String[]{"lessonforge_missions", "lessonforge_conversations", "lessonforge_messages", "lessonforge_context_files", "lessonforge_submissions"}) {
                assertTrue(migration.contains("create table " + table), table);
            }
        }
        assertTrue(postgresql.contains("description text not null"));
        assertTrue(postgresql.contains("content text not null"));
        assertTrue(postgresql.contains("review_note text"));
    }

    private String read(String path) throws IOException {
        try (var input = new ClassPathResource(path).getInputStream()) {
            return new String(input.readAllBytes(), StandardCharsets.UTF_8);
        }
    }
}
