create table model_connections (
    id bigint generated by default as identity primary key,
    owner_user_id bigint not null,
    name varchar(120) not null,
    protocol varchar(32) not null,
    base_url varchar(2048) not null,
    model_id varchar(128) not null,
    encrypted_api_key clob not null,
    key_hint varchar(4) not null,
    enabled boolean not null,
    verification_status varchar(16) not null,
    last_verified_at timestamp(6),
    last_used_at timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_model_connections_owner_name unique (owner_user_id, name)
);
create index idx_model_connections_owner on model_connections (owner_user_id);
