create table model_call_audits (
    id bigint generated by default as identity primary key,
    request_id varchar(64) not null,
    actor_user_id bigint not null,
    model_connection_id bigint not null,
    protocol varchar(32) not null,
    base_url_host varchar(255) not null,
    model_id varchar(128) not null,
    purpose varchar(64) not null,
    credential_source varchar(32) not null,
    http_status integer not null,
    latency_ms bigint not null,
    occurred_at timestamp(6) not null
);
create index idx_model_call_audits_actor_time on model_call_audits (actor_user_id, occurred_at);
create index idx_model_call_audits_connection_time on model_call_audits (model_connection_id, occurred_at);
