create table lessonforge_material_bindings (
    id bigint generated by default as identity primary key,
    created_at timestamp(6), updated_at timestamp(6),
    mission_id bigint not null,
    mission_file_id bigint not null,
    owner_user_id bigint not null,
    actor_user_id bigint not null,
    rag_project_id bigint not null references projects(id),
    rag_material_id bigint not null references uploaded_materials(id),
    source_sha256 varchar(64) not null,
    source_size bigint not null,
    original_filename varchar(255) not null,
    binding_status varchar(20) not null,
    constraint uk_lf_material_identity unique (mission_file_id, source_sha256),
    constraint ck_lf_material_sha check (regexp_like(source_sha256, '^[0-9a-fA-F]{64}$')),
    constraint ck_lf_material_size check (source_size > 0)
);
create index ix_lf_material_binding_mission on lessonforge_material_bindings(mission_id, created_at, id);
create index ix_lf_material_binding_project on lessonforge_material_bindings(rag_project_id, rag_material_id);
