-- Baseline for the current H2 file database. Clean databases execute this before the stage 3/4 migration.
-- Existing non-empty databases baseline at version 1 and then apply V2.
create table ai_api_credentials (
        active boolean not null,
        key_hint varchar(4) not null,
        key_slot integer not null,
        key_version integer not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        last_used_at timestamp(6),
        owner_user_id bigint not null,
        updated_at timestamp(6),
        provider varchar(32) not null,
        encrypted_value clob not null,
        primary key (id),
        constraint uk_ai_api_credential_owner_provider_slot unique (owner_user_id, provider, key_slot)
    );

    create table app_users (
        enabled boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        username varchar(50) not null unique,
        display_name varchar(100) not null,
        password_hash varchar(100) not null,
        primary key (id)
    );

    create table approval_requests (
        active_artifact_version_id bigint,
        artifact_version_id bigint not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        project_id bigint not null,
        reviewed_at timestamp(6),
        reviewer_id bigint not null,
        submitted_at timestamp(6) not null,
        submitted_by bigint not null,
        updated_at timestamp(6),
        review_note varchar(5000),
        status enum ('APPROVED','CANCELLED','REVISION_REQUIRED','SUBMITTED') not null,
        primary key (id),
        constraint uk_active_artifact_approval unique (active_artifact_version_id)
    );

    create table artifact_versions (
        final_version boolean,
        version_number integer,
        created_at timestamp(6),
        generation_plan_id bigint,
        id bigint generated by default as identity,
        project_id bigint,
        description varchar(255),
        primary key (id)
    );

    create table clarification_questions (
        answered_at timestamp(6),
        created_at timestamp(6),
        id bigint generated by default as identity,
        project_id bigint,
        question varchar(255),
        question_id varchar(255),
        target_field varchar(255),
        status enum ('ANSWERED','OBSOLETE','PENDING'),
        primary key (id),
        constraint uk_clarification_question_question_id unique (question_id)
    );

    create table class_groups (
        student_count integer not null,
        course_id bigint not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        cohort varchar(80),
        class_name varchar(120) not null,
        primary key (id),
        constraint uk_course_class_name unique (course_id, class_name)
    );

    create table class_memberships (
        class_id bigint not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        student_id bigint not null,
        primary key (id),
        constraint uk_class_student unique (class_id, student_id)
    );

    create table courses (
        created_at timestamp(6),
        created_by bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        course_code varchar(40) not null unique,
        course_name varchar(120) not null,
        description varchar(500),
        primary key (id)
    );

    create table dialog_messages (
        round_no integer,
        created_at timestamp(6),
        id bigint generated by default as identity,
        project_id bigint,
        session_id varchar(255),
        content CLOB,
        role enum ('ASSISTANT','SYSTEM','TEACHER'),
        primary key (id)
    );

    create table edit_records (
        created_at timestamp(6),
        id bigint generated by default as identity,
        project_id bigint,
        version_id bigint,
        edit_instruction CLOB,
        edit_result CLOB,
        primary key (id)
    );

    create table export_records (
        created_at timestamp(6),
        id bigint generated by default as identity,
        project_id bigint,
        file_name varchar(255),
        file_path varchar(255),
        export_type enum ('DOCX','INTERACTION','PACKAGE','PPTX'),
        primary key (id)
    );

    create table generated_artifacts (
        schema_version integer,
        created_at timestamp(6),
        generation_plan_id bigint,
        id bigint generated by default as identity,
        project_id bigint,
        version_id bigint,
        file_path varchar(255),
        title varchar(255),
        artifact_type enum ('DOCX','INTERACTION','PPT'),
        content_json CLOB,
        primary key (id)
    );

    create table generation_plans (
        confirmed boolean,
        created_at timestamp(6),
        id bigint generated by default as identity,
        project_id bigint,
        teaching_intent_id bigint,
        updated_at timestamp(6),
        provider varchar(255),
        doc_outline CLOB,
        interaction_plan CLOB,
        ppt_outline CLOB,
        primary key (id)
    );

    create table knowledge_chunk_keywords (
        sort_order integer not null,
        chunk_id bigint not null,
        keyword_value varchar(255),
        primary key (sort_order, chunk_id)
    );

    create table knowledge_chunk_usages (
        sort_order integer not null,
        chunk_id bigint not null,
        usage_type enum ('CASE_MATERIAL','CASE_REFERENCE','CHAPTER_STRUCTURE','EXERCISE_SOURCE','IMAGE_ASSET','KNOWLEDGE_POINT','KNOWLEDGE_SUPPLEMENT','STYLE_REFERENCE','TEXTBOOK_BASIS','VIDEO_CONTENT'),
        primary key (sort_order, chunk_id)
    );

    create table knowledge_chunks (
        chunk_no integer,
        created_at timestamp(6),
        id bigint generated by default as identity,
        material_id bigint,
        project_id bigint,
        source_filename varchar(255),
        title varchar(255),
        content CLOB,
        primary key (id),
        constraint uk_knowledge_chunk_material_no unique (material_id, chunk_no)
    );

    create table material_purposes (
        created_at timestamp(6),
        id bigint generated by default as identity,
        material_id bigint,
        project_id bigint,
        purpose_description varchar(255),
        purpose_type enum ('CASE_MATERIAL','CASE_REFERENCE','CHAPTER_STRUCTURE','EXERCISE_SOURCE','IMAGE_ASSET','KNOWLEDGE_POINT','KNOWLEDGE_SUPPLEMENT','STYLE_REFERENCE','TEXTBOOK_BASIS','VIDEO_CONTENT'),
        primary key (id)
    );

    create table parse_result_keywords (
        parse_result_id bigint not null,
        keyword_value varchar(255)
    );

    create table parse_result_sections (
        section_order integer not null,
        parse_result_id bigint not null,
        section_value CLOB,
        primary key (section_order, parse_result_id)
    );

    create table parse_result_stages (
        parse_result_id bigint not null,
        stage_value varchar(255)
    );

    create table parse_results (
        chunk_count integer,
        page_count integer,
        created_at timestamp(6),
        id bigint generated by default as identity,
        material_id bigint,
        parse_duration_ms bigint,
        parsed_at timestamp(6),
        updated_at timestamp(6),
        failure_reason varchar(255),
        extracted_text CLOB,
        parse_status enum ('FAILED','NOT_STARTED','PROCESSING','SUCCEEDED'),
        summary CLOB,
        primary key (id)
    );

    create table project_visits (
        visit_count integer not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        last_visited_at timestamp(6) not null,
        project_id bigint not null,
        user_id bigint not null,
        primary key (id),
        constraint uk_project_visit_user_project unique (user_id, project_id)
    );

    create table projects (
        lesson_duration_minutes integer,
        created_at timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        owner_user_id bigint,
        updated_at timestamp(6),
        chapter_topic varchar(255),
        course_name varchar(255),
        project_description varchar(255),
        project_name varchar(255),
        target_audience varchar(255),
        generation_mode enum ('ECONOMY','HIGH_QUALITY','MOCK','QUALITY','STANDARD'),
        status enum ('CREATED','FINALIZED','GENERATED','INTENT_CONFIRMED','MATERIAL_READY','REQUIREMENT_CONFIRMED'),
        primary key (id)
    );

    create table publications (
        approval_request_id bigint not null,
        artifact_version_id bigint not null,
        class_id bigint not null,
        course_id bigint not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        project_id bigint not null,
        published_at timestamp(6) not null,
        published_by bigint not null,
        withdrawn_at timestamp(6),
        title varchar(200) not null,
        summary varchar(5000),
        status enum ('PUBLISHED','WITHDRAWN') not null,
        primary key (id),
        constraint uk_publication_approval_class unique (approval_request_id, class_id)
    );

    create table question_answers (
        created_at timestamp(6),
        id bigint generated by default as identity,
        question_id bigint not null,
        teacher_id bigint not null,
        content varchar(5000) not null,
        primary key (id)
    );

    create table questions (
        answered_at timestamp(6),
        closed_at timestamp(6),
        created_at timestamp(6),
        id bigint generated by default as identity,
        project_id bigint not null,
        publication_id bigint not null,
        student_id bigint not null,
        updated_at timestamp(6),
        title varchar(200) not null,
        content varchar(5000) not null,
        status enum ('ANSWERED','CLOSED','OPEN') not null,
        primary key (id)
    );

    create table requirement_input_output_types (
        sort_order integer not null,
        requirement_id bigint not null,
        output_type varchar(255),
        primary key (sort_order, requirement_id)
    );

    create table requirement_inputs (
        created_at timestamp(6),
        id bigint generated by default as identity,
        project_id bigint,
        updated_at timestamp(6),
        baseline_level varchar(255),
        grade_level varchar(255),
        interaction_type varchar(255),
        lesson_duration varchar(255),
        style_preference varchar(255),
        subject varchar(255),
        topic varchar(255),
        content CLOB,
        difficult_points CLOB,
        input_type enum ('CLOB','VOICE'),
        key_points CLOB,
        raw_requirement_text CLOB,
        teaching_goals CLOB,
        primary key (id)
    );

    create table requirement_summaries (
        confirmed_at timestamp(6),
        created_at timestamp(6),
        id bigint generated by default as identity,
        project_id bigint,
        source_requirement_id bigint,
        updated_at timestamp(6),
        baseline_level varchar(255),
        grade_level varchar(255),
        interaction_type varchar(255),
        lesson_duration varchar(255),
        style_preference varchar(255),
        subject varchar(255),
        topic varchar(255),
        difficult_points CLOB,
        generation_mode enum ('ECONOMY','HIGH_QUALITY','MOCK','QUALITY','STANDARD'),
        key_points CLOB,
        status enum ('CONFIRMED','DRAFT'),
        teaching_goals CLOB,
        primary key (id)
    );

    create table requirement_summary_output_types (
        sort_order integer not null,
        summary_id bigint not null,
        output_type varchar(255),
        primary key (sort_order, summary_id)
    );

    create table teaching_intent_evidence (
        sort_order integer not null,
        intent_id bigint not null,
        knowledge_chunk_id bigint,
        material_id bigint,
        hit_reason varchar(255),
        source_filename varchar(255),
        usage_types varchar(255),
        content_excerpt CLOB,
        primary key (sort_order, intent_id)
    );

    create table teaching_intent_generation_goals (
        sort_order integer not null,
        intent_id bigint not null,
        goal_value varchar(255),
        primary key (sort_order, intent_id)
    );

    create table teaching_intent_output_types (
        sort_order integer not null,
        intent_id bigint not null,
        output_type varchar(255),
        primary key (sort_order, intent_id)
    );

    create table teaching_intent_supplemental_basis (
        sort_order integer not null,
        intent_id bigint not null,
        basis_value varchar(255),
        primary key (sort_order, intent_id)
    );

    create table teaching_intents (
        total_hours integer,
        confirmed_at timestamp(6),
        created_at timestamp(6),
        id bigint generated by default as identity,
        project_id bigint,
        requirement_summary_id bigint,
        updated_at timestamp(6),
        primary_basis varchar(255),
        style_preference varchar(255),
        target_audience varchar(255),
        content_basis CLOB,
        generation_goal CLOB,
        interaction_mode CLOB,
        notes CLOB,
        status enum ('CONFIRMED','DRAFT'),
        teaching_approach CLOB,
        teaching_format CLOB,
        primary key (id)
    );

    create table teaching_tasks (
        assignee_id bigint not null,
        class_id bigint,
        completed_at timestamp(6),
        course_id bigint not null,
        created_at timestamp(6),
        created_by bigint not null,
        due_at timestamp(6) not null,
        id bigint generated by default as identity,
        linked_project_id bigint,
        submitted_at timestamp(6),
        updated_at timestamp(6),
        chapter_title varchar(160) not null,
        task_name varchar(160) not null,
        priority enum ('HIGH','LOW','MEDIUM','URGENT') not null,
        requirements clob not null,
        review_note clob,
        submission_note clob,
        task_status enum ('ASSIGNED','CANCELLED','COMPLETED','DRAFT','IN_PROGRESS','REVISION_REQUIRED','SUBMITTED') not null,
        primary key (id)
    );

    create table uploaded_materials (
        created_at timestamp(6),
        file_size bigint,
        id bigint generated by default as identity,
        project_id bigint,
        updated_at timestamp(6),
        content_type varchar(255),
        file_extension varchar(255),
        file_name varchar(255),
        file_path varchar(255),
        material_description varchar(255),
        original_file_name varchar(255),
        file_type enum ('DOCX','IMAGE','JPEG','JPG','MD','MP4','OTHER','PDF','PNG','PPT','PPTX','TXT','VIDEO','WORD','XLSX'),
        parse_status enum ('FAILED','NOT_STARTED','PROCESSING','SUCCEEDED'),
        upload_status enum ('CONFIRMED','FAILED','PARSED','UPLOADED'),
        primary key (id)
    );

    create table user_role_assignments (
        created_at timestamp(6),
        id bigint generated by default as identity,
        user_id bigint not null,
        role enum ('LEADER','STUDENT','TEACHER') not null,
        primary key (id),
        constraint uk_user_role unique (user_id, role)
    );

    create table user_sessions (
        created_at timestamp(6),
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        last_used_at timestamp(6) not null,
        revoked_at timestamp(6),
        user_id bigint not null,
        token_hash varchar(64) not null unique,
        active_role enum ('LEADER','STUDENT','TEACHER') not null,
        primary key (id)
    );

    create index idx_publication_approval_class 
       on publications (approval_request_id, class_id);

    create index idx_publication_class_status 
       on publications (class_id, status);

    create index idx_question_answer_question_created 
       on question_answers (question_id, created_at);

    create index idx_question_student_updated 
       on questions (student_id, updated_at);

    create index idx_question_project_updated 
       on questions (project_id, updated_at);

    create index idx_question_publication_updated 
       on questions (publication_id, updated_at);

    alter table if exists knowledge_chunk_keywords 
       add constraint FKv6nbetvuaig5w7bmr8jmel0i 
       foreign key (chunk_id) 
       references knowledge_chunks;

    alter table if exists knowledge_chunk_usages 
       add constraint FKexhdepcmxy1evaqq038ihpr9e 
       foreign key (chunk_id) 
       references knowledge_chunks;

    alter table if exists parse_result_keywords 
       add constraint FK54wsm9heyjaa9hk0b3xpoah35 
       foreign key (parse_result_id) 
       references parse_results;

    alter table if exists parse_result_sections 
       add constraint FKtg3r7hppvhgqnw3jyn6v1svy6 
       foreign key (parse_result_id) 
       references parse_results;

    alter table if exists parse_result_stages 
       add constraint FK4hqaxjxl9wnb935qfnjvt3ktg 
       foreign key (parse_result_id) 
       references parse_results;

    alter table if exists requirement_input_output_types 
       add constraint FK96fjmb17aufp4hrrwgs3hfjwr 
       foreign key (requirement_id) 
       references requirement_inputs;

    alter table if exists requirement_summary_output_types 
       add constraint FKbvhyh77gimg9lyne5o77bvxtc 
       foreign key (summary_id) 
       references requirement_summaries;

    alter table if exists teaching_intent_evidence 
       add constraint FKaihuaokbsn5iiu2o0xidcu4b9 
       foreign key (intent_id) 
       references teaching_intents;

    alter table if exists teaching_intent_generation_goals 
       add constraint FK5gl33fq384d4tt8rw9l88bjt2 
       foreign key (intent_id) 
       references teaching_intents;

    alter table if exists teaching_intent_output_types 
       add constraint FKgjvg8vgy58ivmjnhng9yo7h20 
       foreign key (intent_id) 
       references teaching_intents;

    alter table if exists teaching_intent_supplemental_basis 
       add constraint FK1lx04fxlykoxo9c3btp171ymh 
       foreign key (intent_id) 
       references teaching_intents;



