-- Stage 3/4 versioned schema. The base application schema (including projects)
-- is expected to exist before this migration is enabled.
CREATE TABLE IF NOT EXISTS templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    project_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    created_by_user_id BIGINT,
    active_source_version_id BIGINT,
    CONSTRAINT uk_templates_project_name UNIQUE (project_id, name),
    CONSTRAINT fk_templates_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE IF NOT EXISTS template_source_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    template_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    version_number INT NOT NULL,
    created_by_user_id BIGINT,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    storage_key VARCHAR(512) NOT NULL,
    content_type VARCHAR(160) NOT NULL,
    file_size BIGINT,
    sha256 VARCHAR(64) NOT NULL,
    parse_status VARCHAR(32),
    render_status VARCHAR(32),
    analysis_status VARCHAR(32),
    entity_version BIGINT,
    CONSTRAINT uk_template_sources_template_version UNIQUE (template_id, version_number),
    CONSTRAINT uk_template_sources_template_sha256 UNIQUE (template_id, sha256),
    CONSTRAINT fk_template_sources_template FOREIGN KEY (template_id) REFERENCES templates(id),
    CONSTRAINT fk_template_sources_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE IF NOT EXISTS template_processing_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    template_id BIGINT NOT NULL,
    source_version_id BIGINT NOT NULL,
    attempt INT NOT NULL,
    operation VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    adapter VARCHAR(120),
    output_reference VARCHAR(512),
    failure_reason CLOB,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    CONSTRAINT fk_processing_runs_source FOREIGN KEY (source_version_id) REFERENCES template_source_versions(id)
);

CREATE TABLE IF NOT EXISTS template_structural_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    template_id BIGINT NOT NULL,
    source_version_id BIGINT NOT NULL,
    processing_run_id BIGINT NOT NULL,
    slide_count INT,
    checksum VARCHAR(64) NOT NULL,
    snapshot_json CLOB NOT NULL,
    CONSTRAINT fk_snapshots_source FOREIGN KEY (source_version_id) REFERENCES template_source_versions(id),
    CONSTRAINT fk_snapshots_run FOREIGN KEY (processing_run_id) REFERENCES template_processing_runs(id)
);

CREATE TABLE IF NOT EXISTS template_rendered_slide_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    template_id BIGINT NOT NULL,
    source_version_id BIGINT NOT NULL,
    processing_run_id BIGINT NOT NULL,
    slide_count INT,
    status VARCHAR(32),
    preview_reference VARCHAR(512),
    status_message VARCHAR(500),
    CONSTRAINT fk_rendered_sets_source FOREIGN KEY (source_version_id) REFERENCES template_source_versions(id),
    CONSTRAINT fk_rendered_sets_run FOREIGN KEY (processing_run_id) REFERENCES template_processing_runs(id)
);

CREATE TABLE IF NOT EXISTS template_profile_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    template_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    source_version_id BIGINT NOT NULL,
    parent_profile_version_id BIGINT,
    version_number INT NOT NULL,
    created_by_user_id BIGINT,
    owned_by_teacher_id BIGINT,
    origin VARCHAR(32) NOT NULL,
    parser_snapshot_checksum VARCHAR(64),
    renderer_status VARCHAR(32),
    analyzer_status VARCHAR(32),
    status VARCHAR(32) NOT NULL,
    checksum VARCHAR(64) NOT NULL,
    capability_view_version INT NOT NULL,
    capability_view_checksum VARCHAR(64) NOT NULL,
    profile_json CLOB NOT NULL,
    capability_view_json CLOB NOT NULL,
    teacher_edited_at TIMESTAMP,
    confirmed_at TIMESTAMP,
    confirmed_checksum VARCHAR(64),
    entity_version BIGINT,
    CONSTRAINT uk_template_profiles_template_version UNIQUE (template_id, version_number),
    CONSTRAINT fk_profiles_template FOREIGN KEY (template_id) REFERENCES templates(id),
    CONSTRAINT fk_profiles_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_profiles_source FOREIGN KEY (source_version_id) REFERENCES template_source_versions(id)
);

CREATE TABLE IF NOT EXISTS template_profile_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    template_id BIGINT NOT NULL,
    profile_version_id BIGINT NOT NULL,
    reviewer_user_id BIGINT,
    action VARCHAR(32) NOT NULL,
    checksum_at_action VARCHAR(64) NOT NULL,
    note VARCHAR(500),
    CONSTRAINT fk_profile_reviews_profile FOREIGN KEY (profile_version_id) REFERENCES template_profile_versions(id)
);

CREATE TABLE IF NOT EXISTS ppt_specification_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    specification_id VARCHAR(128) NOT NULL,
    project_id BIGINT NOT NULL,
    version_number INT NOT NULL,
    status VARCHAR(16) NOT NULL,
    contract_version VARCHAR(16) NOT NULL,
    template_profile_id VARCHAR(128) NOT NULL,
    template_profile_version INT NOT NULL,
    template_profile_checksum VARCHAR(64),
    template_capability_view_version INT NOT NULL,
    template_capability_view_checksum VARCHAR(64) NOT NULL,
    target_slide_count INT NOT NULL,
    slide_count_tolerance INT NOT NULL,
    locale VARCHAR(32) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    model VARCHAR(128) NOT NULL,
    ai_supplement_policy VARCHAR(32) NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    submitted_by BIGINT,
    submitted_at TIMESTAMP,
    submitted_checksum VARCHAR(64),
    locked_by BIGINT,
    locked_at TIMESTAMP,
    checksum VARCHAR(64) NOT NULL,
    returned_from_version INT,
    return_reason VARCHAR(2000),
    teacher_editing_at TIMESTAMP,
    entity_version BIGINT NOT NULL,
    CONSTRAINT uk_ppt_specifications_project_version UNIQUE (project_id, version_number),
    CONSTRAINT fk_ppt_specifications_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE IF NOT EXISTS ppt_specification_slides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id BIGINT NOT NULL,
    slide_id VARCHAR(128) NOT NULL,
    position INT NOT NULL,
    page_number INT NOT NULL,
    title VARCHAR(500) NOT NULL,
    teaching_goal VARCHAR(2000) NOT NULL,
    semantic_layout_json CLOB NOT NULL,
    notes VARCHAR(2000),
    CONSTRAINT fk_ppt_slides_version FOREIGN KEY (version_id) REFERENCES ppt_specification_versions(id)
);
CREATE TABLE IF NOT EXISTS ppt_specification_content_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slide_id BIGINT NOT NULL,
    block_id VARCHAR(128) NOT NULL,
    position INT NOT NULL,
    type VARCHAR(16) NOT NULL,
    content CLOB NOT NULL,
    source_type VARCHAR(16) NOT NULL,
    source_reference VARCHAR(500) NOT NULL,
    locked BOOLEAN NOT NULL,
    CONSTRAINT fk_ppt_blocks_slide FOREIGN KEY (slide_id) REFERENCES ppt_specification_slides(id)
);
CREATE TABLE IF NOT EXISTS ppt_specification_asset_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slide_id BIGINT NOT NULL,
    asset_id VARCHAR(128) NOT NULL,
    position INT NOT NULL,
    asset_type VARCHAR(16) NOT NULL,
    source VARCHAR(500) NOT NULL,
    approval_status VARCHAR(16) NOT NULL,
    required BOOLEAN NOT NULL,
    placement_intent VARCHAR(16) NOT NULL,
    CONSTRAINT fk_ppt_assets_slide FOREIGN KEY (slide_id) REFERENCES ppt_specification_slides(id)
);
CREATE TABLE IF NOT EXISTS ppt_specification_provenance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slide_id BIGINT NOT NULL,
    position INT NOT NULL,
    source_type VARCHAR(16) NOT NULL,
    source_reference VARCHAR(500) NOT NULL,
    CONSTRAINT fk_ppt_provenance_slide FOREIGN KEY (slide_id) REFERENCES ppt_specification_slides(id)
);

CREATE INDEX IF NOT EXISTS ix_template_sources_project ON template_source_versions(project_id, template_id);
CREATE INDEX IF NOT EXISTS ix_template_profiles_project_status ON template_profile_versions(project_id, template_id, status);
CREATE INDEX IF NOT EXISTS ix_ppt_specifications_project_status ON ppt_specification_versions(project_id, status);

CREATE TABLE IF NOT EXISTS planning_agent_traces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    project_id BIGINT NOT NULL,
    run_id VARCHAR(36) NOT NULL,
    trace_id VARCHAR(36) NOT NULL,
    operation VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    requested_provider VARCHAR(32),
    used_provider VARCHAR(128),
    used_model VARCHAR(128),
    capability_view_checksum VARCHAR(64),
    input_checksum VARCHAR(64),
    output_checksum VARCHAR(64),
    rejection_reason VARCHAR(64),
    completed_at TIMESTAMP,
    CONSTRAINT uk_planning_trace_id UNIQUE (trace_id),
    CONSTRAINT fk_planning_trace_project FOREIGN KEY (project_id) REFERENCES projects(id)
);
CREATE INDEX IF NOT EXISTS ix_planning_traces_project ON planning_agent_traces(project_id, created_at);
CREATE INDEX IF NOT EXISTS ix_planning_traces_run ON planning_agent_traces(run_id);
