CREATE TABLE IF NOT EXISTS template_analysis_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    template_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    source_version_id BIGINT NOT NULL,
    owner_user_id BIGINT,
    processing_run_id BIGINT,
    analysis_run_id VARCHAR(128) NOT NULL UNIQUE,
    source_sha256 VARCHAR(64) NOT NULL,
    parser_snapshot_checksum VARCHAR(64),
    rendered_slide_set_id BIGINT,
    rendered_preview_reference VARCHAR(512),
    rendered_output_sha256 VARCHAR(64),
    rendered_output_size_bytes BIGINT,
    adapter VARCHAR(120),
    adapter_version VARCHAR(120),
    provider VARCHAR(64),
    model VARCHAR(128),
    input_sha256 VARCHAR(64),
    output_sha256 VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    candidate_profile_json CLOB,
    failure_reason CLOB
);

CREATE INDEX IF NOT EXISTS idx_template_analysis_source
    ON template_analysis_results(source_version_id, created_at, id);
