create table lessonforge_missions (
    id bigint generated by default as identity primary key,
    created_at timestamp(6), updated_at timestamp(6),
    title varchar(200) not null, description text not null,
    assigned_teacher_id bigint not null, created_by_leader_id bigint not null,
    deadline timestamp(6), status varchar(20) not null,
    rejection_reason text, rejected_at timestamp(6), selected_model_connection_id bigint
);
create index ix_lf_missions_teacher on lessonforge_missions(assigned_teacher_id, updated_at);
create index ix_lf_missions_leader on lessonforge_missions(created_by_leader_id, updated_at);

create table lessonforge_conversations (
    id bigint generated by default as identity primary key,
    created_at timestamp(6), updated_at timestamp(6), mission_id bigint not null,
    constraint uk_lf_conversation_mission unique (mission_id)
);
create table lessonforge_messages (
    id bigint generated by default as identity primary key,
    created_at timestamp(6), mission_id bigint not null, conversation_id bigint not null,
    sender_id bigint not null, sender_role varchar(20) not null, content text not null
);
create index ix_lf_messages_mission on lessonforge_messages(mission_id, created_at, id);

create table lessonforge_context_files (
    id bigint generated by default as identity primary key,
    created_at timestamp(6), updated_at timestamp(6), mission_id bigint not null,
    uploaded_by bigint not null, original_file_name varchar(255) not null,
    content_type varchar(255) not null, file_extension varchar(16) not null,
    file_size bigint not null, sha256 varchar(64) not null, storage_key varchar(500) not null,
    kind varchar(20) not null, failure_reason text
);
create index ix_lf_context_files_mission on lessonforge_context_files(mission_id, created_at, id);

create table lessonforge_submissions (
    id bigint generated by default as identity primary key,
    created_at timestamp(6), updated_at timestamp(6), mission_id bigint not null,
    uploaded_by bigint not null, reviewer_id bigint not null,
    original_file_name varchar(255) not null, content_type varchar(255) not null,
    file_size bigint not null, sha256 varchar(64) not null, storage_key varchar(500) not null,
    status varchar(20) not null, rating integer, review_note text, reviewed_at timestamp(6),
    constraint ck_lf_submission_rating check (rating is null or rating between 1 and 5)
);
create index ix_lf_submissions_mission on lessonforge_submissions(mission_id, created_at);
