-- PostgreSQL Stage 8 candidate/review/approved manifest schema. Credential plaintext is intentionally absent.
CREATE TABLE IF NOT EXISTS candidate_assets (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TIMESTAMP, updated_at TIMESTAMP,
 project_id BIGINT NOT NULL REFERENCES projects(id), owner_user_id BIGINT NOT NULL, asset_key VARCHAR(128) NOT NULL,
 version_number INT NOT NULL, requirement_key VARCHAR(128) NOT NULL, placement_intent VARCHAR(32) NOT NULL,
 source_type VARCHAR(32) NOT NULL, source_reference VARCHAR(500) NOT NULL, storage_key VARCHAR(512) NOT NULL,
 original_file_reference VARCHAR(128) NOT NULL, mime_type VARCHAR(160) NOT NULL, file_size BIGINT NOT NULL,
 sha256 VARCHAR(64) NOT NULL, provider VARCHAR(32) NOT NULL, model VARCHAR(128) NOT NULL, status VARCHAR(16) NOT NULL,
 reviewer_user_id BIGINT, reviewed_at TIMESTAMP, review_reason VARCHAR(1000), entity_version BIGINT NOT NULL,
 CONSTRAINT uk_candidate_asset_version UNIQUE(project_id, asset_key, version_number)
);
CREATE INDEX IF NOT EXISTS ix_candidate_assets_project_status ON candidate_assets(project_id, status);
CREATE TABLE IF NOT EXISTS approved_asset_manifests (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TIMESTAMP NOT NULL,
 project_id BIGINT NOT NULL REFERENCES projects(id), owner_user_id BIGINT NOT NULL, candidate_asset_id BIGINT NOT NULL REFERENCES candidate_assets(id),
 asset_key VARCHAR(128) NOT NULL, active_key VARCHAR(128), manifest_version INT NOT NULL, candidate_version INT NOT NULL, requirement_key VARCHAR(128) NOT NULL,
 placement_intent VARCHAR(32) NOT NULL, source_type VARCHAR(32) NOT NULL, source_reference VARCHAR(500) NOT NULL,
 storage_key VARCHAR(512) NOT NULL, mime_type VARCHAR(160) NOT NULL, file_size BIGINT NOT NULL, sha256 VARCHAR(64) NOT NULL, approved_file_last_modified_utc VARCHAR(64),
 provider VARCHAR(32) NOT NULL, model VARCHAR(128) NOT NULL, approved_by BIGINT NOT NULL, approved_at TIMESTAMP NOT NULL,
 status VARCHAR(16) NOT NULL, supersedes_manifest_id BIGINT REFERENCES approved_asset_manifests(id), manifest_checksum VARCHAR(64) NOT NULL,
 entity_version BIGINT NOT NULL, CONSTRAINT uk_manifest_asset_version UNIQUE(project_id, asset_key, manifest_version),
 CONSTRAINT uk_manifest_project_active_key UNIQUE(project_id, active_key)
);
CREATE INDEX IF NOT EXISTS ix_manifests_project_asset_status ON approved_asset_manifests(project_id, asset_key, status);
CREATE TABLE IF NOT EXISTS asset_audit_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TIMESTAMP NOT NULL, project_id BIGINT NOT NULL REFERENCES projects(id),
 asset_id BIGINT NOT NULL REFERENCES candidate_assets(id), actor_user_id BIGINT NOT NULL, action VARCHAR(32) NOT NULL,
 from_status VARCHAR(16), to_status VARCHAR(16) NOT NULL, provider VARCHAR(32) NOT NULL, model VARCHAR(128) NOT NULL,
 sha256 VARCHAR(64) NOT NULL, reason VARCHAR(1000), event_checksum VARCHAR(64) NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_asset_audit_project_asset ON asset_audit_events(project_id, asset_id, created_at);
