-- PostgreSQL Stage 9 auditable PPT Engine execution boundary. Credential plaintext is intentionally absent.
CREATE TABLE IF NOT EXISTS ppt_generation_jobs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 created_at TIMESTAMP, updated_at TIMESTAMP,
 project_id BIGINT NOT NULL REFERENCES projects(id), owner_user_id BIGINT NOT NULL, requested_by BIGINT NOT NULL,
 execution_id VARCHAR(128) NOT NULL, idempotency_key VARCHAR(128) NOT NULL,
 specification_version_id BIGINT NOT NULL REFERENCES ppt_specification_versions(id), specification_version INT NOT NULL,
 specification_checksum VARCHAR(64) NOT NULL, template_profile_id BIGINT NOT NULL, template_profile_version INT NOT NULL,
 template_profile_checksum VARCHAR(64) NOT NULL, asset_manifest_version INT NOT NULL, asset_manifest_checksum VARCHAR(64) NOT NULL,
 input_identity_checksum VARCHAR(64) NOT NULL,
 engine_version VARCHAR(128) NOT NULL, status VARCHAR(32) NOT NULL, request_snapshot_json TEXT NOT NULL,
 response_receipt_json TEXT, failure_code VARCHAR(96), failure_message VARCHAR(256), entity_version BIGINT NOT NULL,
 CONSTRAINT uk_ppt_generation_job_project_idempotency UNIQUE(project_id, idempotency_key),
 CONSTRAINT uk_ppt_generation_job_execution UNIQUE(execution_id)
);
CREATE INDEX IF NOT EXISTS ix_ppt_generation_jobs_project_created ON ppt_generation_jobs(project_id, created_at);
